const COUNTRY_NAME_TO_ID = {
    nigeria: 'NG',
    angola: 'AO',
    kenya: 'KE',
    benin: 'BJ',
    ghana: 'GH',
    togo: 'TG',
    cameroon: 'CM',
    uganda: 'UG',
    tanzania: 'TZ',
    rwanda: 'RW',
    zambia: 'ZM',
    zimbabwe: 'ZW',
    namibia: 'NA',
    botswana: 'BW',
    'south africa': 'ZA',
    ethiopia: 'ET',
    egypt: 'EG',
    morocco: 'MA',
    algeria: 'DZ',
    tunisia: 'TN',
    senegal: 'SN',
    mali: 'ML',
    niger: 'NE',
    chad: 'TD',
    congo: 'CG',
    'republic of the congo': 'CG',
    'democratic republic of the congo': 'CD',
    drc: 'CD',
    gabon: 'GA',
    'ivory coast': 'CI',
    "cote d'ivoire": 'CI',
    'cote d’ivoire': 'CI',
    liberia: 'LR',
    'sierra leone': 'SL',
    guinea: 'GN',
    'burkina faso': 'BF',
    mauritania: 'MR',
    sudan: 'SD',
    'south sudan': 'SS',
    somalia: 'SO',
    djibouti: 'DJ',
    eritrea: 'ER',
    mozambique: 'MZ',
    malawi: 'MW',
    madagascar: 'MG',
    lesotho: 'LS',
    eswatini: 'SZ',
    swaziland: 'SZ'
};

module.exports = {
    COUNTRY_NAME_TO_ID
};